### ISSUE TITLE
Use of tuple/struct style variants is inconsistent

### ISSUE THREAD

**Issue by phillord** [phillord/horned-owl#20]
The rules for when to use a tuple, when to use a struct should be made explicit and enforced evenly. I think `ObjectIntersectionOf` and `ObjectUnionOf` should be tuples (since they have only one entity inside).

Also the naming is inconsistent. In most cases, these are short (`from`, `to`), acronym style (`ope`). But then we have `annotation_subject` and `annotation.

This issue was first raised in https://github.com/phillord/horned-owl/issues/18

**Comment by phillord** [comment]
Here is an attempt at a set of explicit rules.

https://github.com/phillord/horned-owl/tree/feature/regularise-naming

There are a number of things that would need changing to follow these, notably `ClassExpression` (most of). Also, I think `super_class` should just become `super` and so forth. Ironically, I did exactly the same thing (with "superclass") when I wrote tawny-owl. You would think I would learn!

**Comment by phillord** [comment]
@althonos I have updated this branch now. All the variables names are consistent (I think) and many shortened. The original issue -- tuple vs C-style structs -- has been fixed also.

I am sure that the consistency is a good thing, but shortening all the variable names is a double edged sword, of course. What do you think, is this a cleaner API, or would variables a bit longer be cleaner?

Normally, I'd be wary of such a change, but now is the time, I think, if I am to do it.

**Comment by althonos** [comment]
I think it is better to have short names, since the typing already gives it away what each field is for anyway. In cases where both types are the same, `sub` and `sup` gives it away already. I can't really see a case of someone using the model directly without being familiar with OWL anyway...

Maybe I can only protest about the choice of `bce` for `Box<ClassExpression>`: the fact the value is boxed does not have any semantic value (in the context of the OWL model), it's just that it **has** to be that way for the type to be sized properly, so IMO `ce` was fine.

**Comment by phillord** [comment]
I agree that `Box` is just for Rust and not for OWL. I changed it because while I was editing things, I started to make strong assumptions about the type based on the name, which don't hold true for `ce` in that position, but do for `ce` in other places.

What about `annotation` -- this remains long. What about `ann`?

**Comment by phillord** [comment]
Think I am happy with this now, so closing. Let me know if you see any bits I missed.
