### ISSUE TITLE
Reexport `curie` crate or `PrefixMapping` to help versioning

### ISSUE THREAD

**Issue by althonos** [phillord/horned-owl#24]
Currently `horned-owl` needs the user to add the `curie` dependency manually with the exact same version as the one used by `horned-owl`, because they need `PrefixMapping` available if they use a parser or a serializer. Because updating the internal `curie` version can break the code relying on it, any `curie` update is to be treated as a breaking change, which is extremely cumbersome.

**Comment by filippodebortoli** [comment]
@althonos has this issue been addressed already?
If not, would this "only" require us to `pub use curie::PrefixMapping` instead of `use curie::PrefixMapping` [here](https://github.com/phillord/horned-owl/blob/d88964b3a83082bcdf8078292f32e37a85e19203/src/io/owx/reader.rs#L1) and [here](https://github.com/phillord/horned-owl/blob/d88964b3a83082bcdf8078292f32e37a85e19203/src/io/owx/writer.rs#L1)?
Or is there more to do, e.g. use wildcards in `cargo.toml` for curie?

**Comment by althonos** [comment]
Maybe add a `pub module curie`, and inside of it `pub use curie::*`, this way downstream users can use `horned_owl::curie::PrefixMapping` and `horned_owl::curie::Curie`.

**Comment by filippodebortoli** [comment]
Fixed by #75.
