### ISSUE TITLE
Strange delay on write to stdout

### ISSUE THREAD

**Issue by jamesaoverton** [phillord/horned-owl#26]
I tried running the tools in `src/bin/` under `main` and `devel`, and I'm getting a weird delay when I pipe to STDOUT. This delay gets larger as the source file gets larger. The same (or similar) delay when we write with py-horned-owl. Here's a bash session (Ubuntu 18.04 inside Docker under macOS... sorry):

```sh
$ curl -LO http://purl.obolibrary.org/obo/obi/obi_core.owl
$ robot convert -i obi_core.owl -o obi_core.owx 
$ time horned-parse obi_core.owx
Parse Complete: "obi_core.owx"

real    0m0.015s
user    0m0.005s
sys     0m0.006s
$ time horned-round obi_core.owx
# skipping file contents
real    0m0.074s
user    0m0.021s
sys     0m0.051s
$ time horned-round obi_core.owx > obi_core_2.owx

real    0m9.618s
user    0m0.070s
sys     0m0.640s
```

The last command is the problem. The real time is way longer than the user and sys time.

My naive guess would be that something is waiting to flush...

**Comment by phillord** [comment]
Hmmm. I get slightly faster performance from the file dump version than that dumping to screen (which is what I would expect).

`time` probably isn't doing what you expect -- it's a bash built in and not a normal command. So it's actually doing:

```
time (horned-round obi_core.owx > obi_core_2.owx)
```

and not

```
time (horned-round obi_core.owx) > obi_core_2.owx
```

which you would normally get. I think you are seeing the time to either flushing or closing `obi_core_2.owx`. If you are writing to the external file system (i.e. not the docker but to a linked one on the host) this might account for it.

What happens if you do:

```
time cat obi_core.owx
time cat obi_core.owx > obi_core_2.owx
```

**Comment by jamesaoverton** [comment]
You're right, it's a Docker volume problem. Running directly under macOS is fast, and running inside Docker but writing just to the container filesystem is fast. Much appreciated!
