### ISSUE TITLE
quick-xml version is long out of date

### ISSUE THREAD

**Issue by phillord-ncl** [phillord/horned-owl#48]
The name space handling is all changed in the new version of the reader so the change is non-trivial unfortunately.

**Comment by filippodebortoli** [comment]
Some observations:

  + `quick_xml::reader::{NsReader,Reader}::read_text()` is only implemented for `NsReader<&'i [u8]>`. This is currently used in line 369 of `reader.rs`. Same goes for `read_to_end()`. The `Read` struct uses `Reader<R: BufRead>', which means that these functions are unavailable.
  + `read_namespaced_event()` is now superseded by `read_resolved_event_into()` ([Link](https://docs.rs/quick-xml/latest/quick_xml/reader/struct.NsReader.html#method.read_resolved_event_into)), which does not require `ns_buf` but returns a tuple `(ns, event)`
  + `e.local_name()` is not returning a `&[u8]` anymore. This can be fixed by changing it to `e.local_name().as_ref()`
  + `decode()` is now available from `r.reader.decoder().decode()`.

These seem to be the biggest issues in `reader.rs` when switching to version `0.25.0`.

**Comment by filippodebortoli** [comment]
A temptative new version of `read_event`:

```rust
fn read_event<A: ForIRI, R: BufRead>(
    read: &mut Read<A, R>,
) -> Result<(Vec<u8>, Event<'static>), HornedError> {
    let r = read
        .reader
        .read_resolved_event_into(&mut read.buf)?;

    match r {
        (_, Event::Eof) => Err(invalid! {
            "Unexpected EoF at {}", read.reader.buffer_position()
        }),
        (resolution, event) => {
            match resolution {
                ResolveResult::Unbound => Ok((Vec::new(), event.into_owned())),
                ResolveResult::Bound(Namespace(ns)) => Ok((ns.to_vec(), event.into_owned())),
                ResolveResult::Unknown(_) => todo!(),
            }
        }
    }
}
```

**Comment by phillord** [comment]
Completed!
