### ISSUE TITLE
Improving IRI handling using `oxiri`

### ISSUE THREAD

**Issue by filippodebortoli** [phillord/horned-owl#56]
At the moment, `horned` comes with its own IRI data structures `IRI` and `IRIString`, plus related traits `ForIRI` and `WithIRI`, methods for IRI resolution, and so on.

I found out that the @oxigraph project provides the [oxiri](https://github.com/oxigraph/oxiri) crate, which comes with most of the features that `horned` seems to need.

@phillord do you think `horned` could benefit from using `oxiri` for handling IRIs or would you stick with the current implementation?

**Comment by althonos** [comment]
This sounds good too since `horned` uses the `curie` crate ATM, which is not super actively maintained...

**Comment by phillord** [comment]
Interesting. I think it is worth discussing the needs behind this first, rather than the specifics of the implementation.


Currently, `IRI` does two things -- at a trait level it is a new type around, well, mostly `Borrow<str>` with a pile of other traits; and, in implementation, it allows interning via `Rc` and `Arc`. 

This addition changes `IRI` to allow do IRI validation as well as giving easy access to all various components of the IRI. I guess this is the key point in it's favour. This makes the library a bit stricter, but improves the ergonomics of IRI manipulation. Oxiri, IIUC, caches all the validation data, so if we check for protocol or host or whatever multiple times, that computation is shared.

There are several against as well. 

It makes the ergonomics of all the `Build` methods more complex, because it requires error handling. 

It makes some lazy code useful for testing not work:

```
use horned_owl::model::*;
fn main() {
    let b = Build::new_rc();
    println!("{:?}", b.class("123"))
}
```

Similarly, it would make parsing OWL which made use of invalid IRIs impossible, since the validation is there at a type level.


We could achieve some of the advantages without the cost. So, if `model::IRI` implemented `TryInto<Iri>`, we could get all the validation and so forth, without the changed interface to `Build`. But, we'd loose the caching of IRI components and the IRI validation would be off by default.

Curie vs oxiri is a slightly separate issue. The current PR doesn't replace curie (although it probably could do). And we could replace curie with oxiri without changing model.

Have I covered everything? In general, it seems like not a bad idea. I am a bit concerned about the ergonomics, since this is a drip-drip kind of thing. On it's own it doesn't seem to bad, but it's easy to make a library harder to use bit at a time. I am not sure about whether IRI validation by design would ever be a problem; I don't know if the OWL API can output invalid IRIs, but there are bound to be some tools out there that do.

@jannahastings Worthing asking Janna also -- this will pass through to python.

**Comment by phillord** [comment]
A lot of this could be achieved by having `ForIRI` implement `TryFrom<String>` rather than `From<String>`. That would make this a compile time choice or nearly so -- `AnonymousIndividual` breaks it slightly but that might be fixable, although it might hopeless complicate the already unwieldy generics.

**Comment by filippodebortoli** [comment]
> Interesting. I think it is worth discussing the needs behind this first, rather than the specifics of the implementation.
> 
> Currently, `IRI` does two things -- at a trait level it is a new type around, well, mostly `Borrow<str>` with a pile of other traits; and, in implementation, it allows interning via `Rc` and `Arc`.
> 

In case IRI validation became a must-have (or want-to-have), it would be possible to switch out `model::IRI` and replace it with `oxiri::Iri` altogether. The only bound over `oxiri::Iri<A>` is `A: Deref<Target = str>`, and trait implementations are provided by `oxiri` for most of the bounds or traits induced from `model::ForIRI`.

> There are several against as well.
> 
> It makes the ergonomics of all the `Build` methods more complex, because it requires error handling.
> 

Fair enough. The quickest workaround I can think of is to implement `Build::iri` as follows:

```rust
    pub fn iri<S: Borrow<str> + Deref<Target=str>>(&self, iri: S) -> IRI<A> {
        let mut cache = self.0.borrow_mut();
        if let Some(cached_iri) = cache.get(iri.borrow()) {
            Ok(cached_iri.clone())
        } else {
            let parsed_iri: Iri<A> = Iri::parse(iri.borrow().to_string().into())
                                     .expect("Invalid IRI found."); // <-- CHANGE HERE.
            cache.insert(parsed_iri.clone().into());
            Ok(parsed_iri.into())
        }
    }
```

This would remove the need for most of the error management and still inform the user whenever they are trying to parse an invalid IRI.

> We could achieve some of the advantages without the cost. So, if `model::IRI` implemented `TryInto<Iri>`, we could get all the validation and so forth, without the changed interface to `Build`. But, we'd loose the caching of IRI components and the IRI validation would be off by default.
> 

What do you mean here? Would you want to add a `IRI::validate(&self) -> Result<Iri<A>, IriParseError>` and leave everything else as it was before?

> Curie vs oxiri is a slightly separate issue. The current PR doesn't replace curie (although it probably could do). And we could replace curie with oxiri without changing model.

How is `curie` currently used within `horned`? Aren't CURIEs and IRIs different things anyway?

**Comment by phillord** [comment]
Oh dear, did I get confused half way through.

If you move `model::IRI` to have `TryFrom<String>` instead of `From<String>` then we'd be nearly able to do this with a generic, but it is only the fallability of construction that distinguishes `model::IRI` from `oxiri::Iri`.

Another solution would be to make a `IriMaybe` struct that would like a bit like this (untested and probably uncompilable) sketch:

```
struct IriMaybe<A:ForIRI> {
      raw: A,
      cached_iri: Option<Iri>
} 

impl TryInto<&Iri> for IriMaybe {
      fn try_into(&self) -> Result<&Iri, Error> {
             match &self.cached_iri {
                   Some(iri) => &iiri,
                   None => {
                         let iri = Iri::parse(&self.raw)?;
                         self.cached_iri = Some(iri);
                         self.try_into()
                   }
       }
}
````


We now have a struct which we can infallably convert  from a `String` but which will fallably give us access to all the methods in `Iri`. So we pay the cost only if we use it. If we don't the string is never parsed. So, it will fit directly into the generic space that we have for `IRI` at the moment. Also for `AnonymousIndividual`, although it will fail to parse in most of these cases.


On `curie` vs `oxiri` -- I only use this in one of the readers. Perhaps they are different, I don't know. Worth checking.

EDIT: hmmm, is the `sophia_iri` crate doing what I suggested above?

**Comment by jannahastings** [comment]
I don't have any thoughts on the best strategy for the `Iri` library. I trust @phillord will know best :-) and will be ready to update py-horned-owl as needed. However, I just wanted to add that I use the `curie` perhaps more extensively in the Python library as I provide access and lookup via CURIE-form IDs.

**Comment by filippodebortoli** [comment]
> If you move `model::IRI` to have `TryFrom<String>` instead of `From<String>` then we'd be nearly able to do this with a generic, but it is only the fallability of construction that distinguishes `model::IRI` from `oxiri::Iri`.

I am confused by this sentence.
I understood that you are proposing to replace `From<String>` with `TryFrom<String>` in the `ForIRI` trait.
In the context of the PR, where

```rust
pub struct IRI<A>(Iri<A>);
```

it is unclear to me how having `TryFrom<String>` would make things easier or more ergonomic.
In the context of the current implementation, where

```rust
pub struct IRI<A>(A);
```

I think that implementing `TryInto<IRI<A>>` would make sense:

```rust
impl<A: ForIRI> TryInto<Iri<A>> for IRI<A> {
    type Error = oxiri::IriParseError;
    fn try_into(self) -> Result<Iri<A>, Self::Error> {
        Iri::parse(self)
    }
}
```

Notice that the `TryInto` trait exposes `try_from(self)` and not `try_from(&self)`, which means that converting `IRI<A>` to `Iri<A>` this way would consume the input. Would this be OK? By looking at the crate code, I have the impression it would be not.

> 
> Another solution would be to make a `IriMaybe` struct that would like a bit like this (untested and probably uncompilable) sketch:
> 
> ```
> struct IriMaybe<A:ForIRI> {
>       raw: A,
>       cached_iri: Option<Iri>
> } 
> 
> impl TryInto<&Iri> for IriMaybe {
>       fn try_into(&self) -> Result<&Iri, Error> {
>              match &self.cached_iri {
>                    Some(iri) => &iiri,
>                    None => {
>                          let iri = Iri::parse(&self.raw)?;
>                          self.cached_iri = Some(iri);
>                          self.try_into()
>                    }
>        }
> }
> ```
> 

This solution would work if `try_into(&mut self)` was available, but it is not.

> EDIT: hmmm, is the `sophia_iri` crate doing what I suggested above?

Kinda. They expose `pub struct Iri<'a>(&'a str)` though, so interning might be lost by using their implementation.

**Comment by phillord** [comment]
I will knock up a rough implementation of `IriMaybe` and see if that will make it clearer. I don't have any data at the moment, but having the IRI validation on by default seems like it will carry a significant load. I guess that also is worth testing. How long would it take to validate the 100,000 or so IRIs that appear in the GO file?

**Comment by phillord** [comment]
Like this.

https://github.com/phillord/horned-owl/tree/scratch/oxiri-adapted

Little or no runtime cost, access to all the oxiri methods, in a (mostly) cached way, but does not validate at point of parsing.

It should be possible to have an eager oxiri wrapper which panics on validation. As noted, there is no way to make this error nicely, only panic. We would have to change `ForIRI` to `TryFrom<String>`; this has the same ergonomics as your approach, but means the validation is not hard coded.

Still, with an eager wrapper, we could performance test this against some real world examples.

**Comment by phillord** [comment]
@jannahastings yeah, I'd forgotten the curie look up stuff. I'll have a look through the code to see what can be done. I'd rather not having two IRI libraries floating around, but it might be a necessity at the moment.

**Comment by filippodebortoli** [comment]
> Like this.
> 
> https://github.com/phillord/horned-owl/tree/scratch/oxiri-adapted
> 
> Little or no runtime cost, access to all the oxiri methods, in a (mostly) cached way, but does not validate at point of parsing.
> 
> It should be possible to have an eager oxiri wrapper which panics on validation. As noted, there is no way to make this error nicely, only panic. We would have to change `ForIRI` to `TryFrom<String>`; this has the same ergonomics as your approach, but means the validation is not hard coded.
> 
> Still, with an eager wrapper, we could performance test this against some real world examples.

I am wondering if implementing `IriMaybe` as a struct rather than an enum is really necessary - I do not understand if caching is in any way lost when using enums. I spun an attempt at having `IriMaybe` as an enum [here](https://github.com/filippodebortoli/horned-owl/commit/22dd8bae90339a9728bf40deb6e64b0a9c2bf79d) ([all the branch here](https://github.com/filippodebortoli/horned-owl/tree/scratch/fdb/irimaybe-enum)).

**Comment by phillord** [comment]
If we do this, though, we have to choose at construction time whether we have validated or not. If our ontology starts with unvalidated IRIs, it will always remain so. The best we can do then is `iri.clone().to_validated()` right? That doesn't seem much easier to me than `oxiri::Iri::parse(iri.underlying())` which does the same thing. If this is what we want, adding a `to_oxiri` method to `iri` should do the trick.

With my approach, the `IRIMaybe` can be queried at any point and once it is, the change happens in place. So we could fetch the oxiri at may places in code. But, it is adding a lot of complexity for something we are not likely to do that often, and if we really want to cache the `model::IRI` -> `oxiri::Iri` mapping it is just a `HashMap` away.

**Comment by filippodebortoli** [comment]
> If we do this, though, we have to choose at construction time whether we have validated or not. If our ontology starts with unvalidated IRIs, it will always remain so. 

In both our implementations of `IriMaybe`, `From<String>` yields an unchecked IRI. So, whenever `IriMaybe::from(s)` is called, both implementations choose to go the unchecked way. I renamed `IriMaybe::new()` to `IriMaybe::new_unchecked()` to better reflect this. I think it is fair to provide the user with `IriMaybe::new_validate()` - if I wanted e.g. to use `horned` to build a syntactic validator for OWL, I would want validation turned on by default. If I trust that my ontology is validated, then I go with `new_unchecked()`. If I initially declare an unchecked IRI and then I want validation, I can call `to_validated()`.

> The best we can do then is `iri.clone().to_validated()` right?

A possibility is to change to

```rust
    pub fn to_validated(&mut self) -> Result<(), IriParseError> {
        if let IRIMaybe::Unchecked(t) = self {
            self = Self::new_validated(t)?;
        }
        Ok(())
    }
```

With that, conversion in-place happens by `iri.to_validated()`. Even if we kept the previous version of `to_validated()` and had `let mut iri: IriMaybe<T>`, calling `iri = iri.to_validated()?;` (or unwrapping) would do the job. From my understanding of ownership, both ways would yield zero-copy validation, since `t` is moved from `Unchecked(t)` into `IriRef::parse(t)?` and there should thus be no heap allocation. 

> That doesn't seem much easier to me than `oxiri::Iri::parse(iri.underlying())` which does the same thing. If this is what we want, adding a `to_oxiri` method to `iri` should do the trick.

If I read the `iri_maybe_to_oxiri()` test in your commit correctly, this is happening with your version of `IriMaybe` too. Or am I misunderstanding your comment here?

> With my approach, the `IRIMaybe` can be queried at any point and once it is, the change happens in place. So we could fetch the oxiri at may places in code.

I agree, but I do not see how that is different in the enum case. Once validation happens, it is cached (I described above how that could happen) and can be used from then on.

One potential drawback of the struct-based `IriMaybe` is that, once validation happened, `raw` is stored _twice_. One copy is in the `raw` field, the other is stored internally by `iri_maybe` (by cloning `raw` and then parsing it). Since `Iri` requires `Deref<Target = str>` exposes `Iri::into_inner(self) -> T`, once validation has happened `as_raw()` and `to_raw()` can use the copy stored within `iri_maybe`.
So, why carrying around `raw` when it is not needed anymore?

> But, it is adding a lot of complexity for something we are not likely to do that often, and if we really want to cache the `model::IRI` -> `oxiri::Iri` mapping it is just a `HashMap` away.
> 
> Is the real solution one a `to_oxiri` method for `IRI`? Very simple, very small.

This could be another valid solution, too. I would need time to think if it is effectively better than having any `IriMaybe`.

**Comment by phillord** [comment]
I think that the big problem of the struct is that the move from being validated to invalidated is, essentially, an internal detail. Really it should use `RefCell` but then we get into the thread safety issues. 

In answer to your question about having two copies (with `raw`) it needs that for the case the IRI is invalid. The `Error` does not contain the IRI, so once you have validated, you can do `eq` or other comparisons.

Turning eager validation on sounds great, but I think will break because we use the same `A` generic for `model::IRI` and `model:AnonymousIndividual`. The latter are expected to be invalid as IRIs.

We can think about this in detail, but for me the real question is why not implement `Into<oxiri::Iri>` and a borrowing equivalent if possible. It is clearly much, much simpler that `IRIMaybe`. Or your original solution `IRI(Iri(A))` 

I cannot think of a reason not to add this (except a new dependency); the question is, therefore, if we do this, is there a reason to add `IRIMaybe`. If not, Occam's razor wins, I think.

**Comment by phillord** [comment]
https://github.com/phillord/horned-owl/tree/scratch/to-oxiri

Something like this. 

Could also add `as_iri_ref_string () -> Iri<String>` to solve some life time issues.
Could also stick this into adaptors namespace (with support for sophia maybe) and feature gate the whole thing to reduce size.

Also, would be nice to remember why I commented out all the tests in model.rs, but I guess that is a different issue!

**Comment by phillord** [comment]
I've added an alternative implementation in a separate namespace also.

**Comment by filippodebortoli** [comment]
Another IRI-related issue: the `vocab` module uses `vocab::IRIString` to e.g. store namespaces. Could it be replaced with `model::IRI` by making `WithIRI<'a>` generic over `A: ForIRI`?

**Comment by phillord** [comment]
Well, I wrote both of those as options. I think we either have `model::as_oxiri()` or `adaptor::as_oxiri()` (obviously without `v2`)

I think that adaptor would have scaling advantages -- I could feature gate it. If we add `sophia_iri` and other packages as they come along, that would be significant. Or I could worry about that when it becomes a problem.

**Comment by phillord** [comment]
Think I go with the adaptor model. Don't want to put all the code in the world into `model.rs`

https://github.com/phillord/horned-owl/tree/feature/to-oxiri
