### ISSUE TITLE
Trait bounds should be tightened

### ISSUE THREAD

**Issue by filippodebortoli** [phillord/horned-owl#87]
This elaborates on #74.

The library currently contains two traits, [`indexed::ForIndex`](https://github.com/phillord/horned-owl/blob/7040db376eef3fdfeb1d6b8e240de1f1fbf27390/src/ontology/indexed.rs#L29) and [`model::ForIRI`](https://github.com/phillord/horned-owl/blob/7040db376eef3fdfeb1d6b8e240de1f1fbf27390/src/model.rs#L123), whose job is to collect trait bounds for types that can be used to build ontology indexes and IRIs.

Currently, many methods require e.g. `A: ForIRI` where it is not strictly necessary.
For instance, `model::Build::new()` should work without any bound on `A`, going from the current implementation to

```rust
pub struct Build<A>(
    RefCell<BTreeSet<IRI<A>>>,
    RefCell<BTreeSet<AnonymousIndividual<A>>>,
);

impl<A> Build<A> {
    pub fn new() -> Build<A> {
        Build(RefCell::new(BTreeSet::new()), RefCell::new(BTreeSet::new()))
    }
}
```

Another example is the implementation of `Clone` for `indexed::OneIndexedOntology` which currently is

```rust
impl<A: ForIRI, AA: ForIndex<A>, I: Clone> Clone for OneIndexedOntology<A, AA, I> {
    fn clone(&self) -> Self {
        OneIndexedOntology(
            self.0.clone(),
            self.1.clone(),
            Default::default(),
        )
    }
}
```

but may be simplified to

```rust
impl<A: Clone, AA, I: Clone> Clone for OneIndexedOntology<A, AA, I> {
    fn clone(&self) -> Self {
        OneIndexedOntology(self.0.clone(), self.1.clone(), Default::default())
    }
}
```

so that `AA` can be fully generic (which makes sense given that we use `PhantomData<AA>` there).

The goal is to remove any reference to `ForIRI` and `ForIndex` where possible, and potentially question whether these traits are necessary at all.

**Comment by phillord** [comment]
I am happy consider this, but I think my concern is that it will bring
significant instability and complexity into the API. Using your
example of `Build`, for instance, we can indeed do this:


```
pub struct Build<A>(
    RefCell<BTreeSet<IRI<A>>>,
    RefCell<BTreeSet<AnonymousIndividual<A>>>,
);

impl<A> Build<A> {
    pub fn new() -> Build<A> {
        Build(RefCell::new(BTreeSet::new()), RefCell::new(BTreeSet::new()))
    }
}
```

Removing the bound from `Build` is indeed given as best practice from Rust, although as the
https://rust-lang.github.io/rfcs/2089-implied-bounds.html RFC says that might change in future.

We can also limit the bound from `new` and that works. But the cost
for this is we now need two `impl` blocks with different bounds. We
can also reduce the bounds on that impl block. The simplest that I
have got this to is:

```
impl<A: AsRef<str> + Borrow<str> + Clone + From<String> + Hash + PartialOrd + Ord> Build<A> {


 pub fn anon<S: Borrow<str>>(&self, s: S) -> AnonymousIndividual<A> {
     ....
 }

....
}
```

which drops `Debug` and `Eq` support; all the other types are
needed. Other parts of the API will not be able to
take `IRI`s that do not fulfil the `Debug` or `Eq` which I think will
be hard a hard to understand compiler error. Further both
`From<String>`, `Hash` and `Clone` are implementation dependent;
theoretically we could change the `Build` implementation to not need
these traits; so picking the minimial bound exposes implementation detail.

Given that any type which is `AsRef<str>` has a naturalistic
implementation of `Debug` and `Eq`, it is hard to see what we have
gained here.

So, I need something clearer -- what would the weaker bound allow on
`Build` allow you to do that you cannot do now?

**Comment by filippodebortoli** [comment]
> I am happy consider this, but I think my concern is that it will bring significant instability and complexity into the API. Using your example of `Build`, for instance, we can indeed do this:
> 
> ```rust
> pub struct Build<A>(
>     RefCell<BTreeSet<IRI<A>>>,
>     RefCell<BTreeSet<AnonymousIndividual<A>>>,
> );
> 
> impl<A> Build<A> {
>     pub fn new() -> Build<A> {
>         Build(RefCell::new(BTreeSet::new()), RefCell::new(BTreeSet::new()))
>     }
> }
> ```
> 
> Removing the bound from `Build` is indeed given as best practice from Rust, although as the https://rust-lang.github.io/rfcs/2089-implied-bounds.html RFC says that might change in future.
> 
> We can also limit the bound from `new` and that works. But the cost for this is we now need two `impl` blocks with different bounds. We can also reduce the bounds on that impl block. The simplest that I have got this to is:
> 
> ```rust
> impl<A: AsRef<str> + Borrow<str> + Clone + From<String> + Hash + PartialOrd + Ord> Build<A> {
> 
> 
>  pub fn anon<S: Borrow<str>>(&self, s: S) -> AnonymousIndividual<A> {
>      ....
>  }
> 
> ....
> }
> ```
> 
> which drops `Debug` and `Eq` support; all the other types are needed. Other parts of the API will not be able to take `IRI`s that do not fulfil the `Debug` or `Eq` which I think will be hard a hard to understand compiler error. Further both `From<String>`, `Hash` and `Clone` are implementation dependent; theoretically we could change the `Build` implementation to not need these traits; so picking the minimial bound exposes implementation detail.
> 
> Given that any type which is `AsRef<str>` has a naturalistic implementation of `Debug` and `Eq`, it is hard to see what we have gained here.
> 

If we just change the implementation of `Build` so that trait bounds are tight and leave it at that, we probably will not gain much.

On the other hand, I get `anon` to work with this set of bounds:

```rust
impl<A: Borrow<str> + Clone + From<String> + Ord> Build<A> {
    pub fn anon<S: Borrow<str>>(&self, s: S) -> AnonymousIndividual<A> {
        let mut cache = self.1.borrow_mut();
        if let Some(anon) = cache.get(s.borrow()) {
            anon.clone()
        } else {
            let anon = AnonymousIndividual(s.borrow().to_string().into());
            cache.insert(anon.clone());
            anon
        }
    }

}
```

and having achieved this, I am asking myself: why is `AnonymousIndividual(s.borrow().to_string().into())` there? Where can I change the code so that `AnonymousIndividual::from(s)` is possible instead, given that we are anyhow consuming `s`? Do I really need `A: From<String>`?

I guess that going further, I may ask myself similar questions throughout the whole `model` module, and I would say that any resulting change is probably beneficial for the usability of the library.

After that, I would assume that it is possible to keep `ForIRI` around and simply use it to define ontologies implementations, so that one knows that then all the builders and indexes work as intended.

That said, I agree that keeping tabs with all these bounds may be complicated, but I would also advocate for the opposite view, where having split requirements yields a more refined indication given by the compiler when errors arise.

 > So, I need something clearer -- what would the weaker bound allow on `Build` allow you to do that you cannot do now?

**Comment by phillord** [comment]
That code snippet doesn't work for me, I am afraid. Does it compile for you? I have just introduced the `impl` block and removed the method from it's existing block.

I agree that we could construct `AnonymousIndividual` in less lines, but this should be the only place we construct them, so I cannot see the gain here in doing this via `From` would be.

**Comment by filippodebortoli** [comment]
> That code snippet doesn't work for me, I am afraid. Does it compile for you? I have just introduced the `impl` block and removed the method from it's existing block.
> 

It compiles on the branch I am working on (see #88).

> I agree that we could construct `AnonymousIndividual` in less lines, but this should be the only place we construct them, so I cannot see the gain here in doing this via `From` would be.

I am more dubious about having to perform a borrow from `S` to `str, then an explicit conversion from `str` to `String` and then another explicit conversion to `A` when we could instead require that there is a more direct relation between `S` and `A`.

In most of the examples shown in the tests, `iri()` or `class()`  or other methods are called on `str`s and in few instances on `String`s, that is why `A: From<S>` comes to my mind.

I am not sure if there can be effective gains in terms of memory allocation in rewriting `iri()` and `anon()`, but I cannot see why requiring `A: From<S>` instead of `A: From<String>` (which is included in `ForIRI` and used mainly for these two methods in `model::Build`) would not be a bad choice.

**Comment by phillord** [comment]
I've started to look through this code now. When I went through the process of making IRI generic, I had found the situation completely painful, which is why I added the ForIRI trait in the first place. I still worry about the introduction of overly complex type signatures and artificial instability.

So far, the situation is not as bad as I thought it would be. In most cases type bounds are obvious to see; so for example we have:

```
impl<A: Deref<Target = str>> Deref for Individual<A> 
```

which is fairly obvious -- we need to be able `Deref A` to be able `Deref Individual`.

I am still worried about some of the longer types that we are getting, though. So far I have found these:

```
<A: Borrow<str> + Clone + From<String> + Ord>
<A: Borrow<str> + PartialEq>
<A: Hash + Ord>
```

(I think the PartialEq ones should probably be Eq also). All of these are covered by the ForIRI type. Now these are slow and painful to type; and I find the compiler error messages quite opaque, so it can be hard to work out what you really need. But at least there are only three different ones; and if they are used repeatedly, we might be able to write more constrainted `ForIRI` type traits. If we made the XML or RDF reader with tigther trait bounds 

I remain concerned, that there is going to be significant
implementation dependency here; for example:

```
impl<A: Clone> From<&IRI<A>> for AnnotationSubject<A> {
    fn from(iri: &IRI<A>) -> AnnotationSubject<A> {
        AnnotationSubject::IRI(iri.clone())
    }
}
```

The underlying requirement for `Clone` here is not as obvious with `Deref` above. I think it is also implementation dependent. This is the obvious implementation, but you can see other implementations of `From<&IRI>` that would not need clone; or would need something else.

And I still remain unclear what we gain from this. Most uses of Horned-OWL with some `A` are going to pass through all the functions that require all of the three complex trait bounds above and many of the single bound functions; pretty quickly `A` is going to need to bound by all of the sub-traits of `ForIRI`.

I need to think more about `Borrow<str>` and `AsRef<str>` -- I still do not really understand these traits fully, but given that `Borrow<str>` implies an implementation for `Ord`, `Eq`, `Hash` and `Debug`, I wonder why `Borrow<str> + Clone + From<String>` for the `ForIRI` trait implementation. `ForIndex` should likewise collapse to `Borrow<AnnotatedComponent> + Clone + From<AnnotatedComponent>`

**Comment by phillord** [comment]
I have thought on this more. The documentation for `Borrow`, `AsRef` and `Deref` is joyfully opaque on the difference between them. But as far as I can see, we should actually be using `Borrow` in most cases because of the assumption that `Eq, `Hash` and `Ord` will work on `A` in the same way as on the referenced `str` type. We should also implement Deref for IRI so that all the `str` methods become available to `IRI` without having to do a `borrow`.

I can't see that there is any technical difficult in this -- we just need to switch `as_ref` calls to `borrow`. The only issue here is pretty_rdf which requires `AsRef` -- but to be honest, I think that the same logic applies here as for horned-owl; pretty_rdf makes extensive use of `Eq, `Hash` and `Ord`. Perhaps if pretty_rdf were `Borrow`, the need for `AsRef` would disappear.

The documentation for `Borrow` only say that `Eq`, `Hash` and `Ord` should work for the implementing type as it does for the borrowed type. It doesn't as far as I can see require that the `Borrow` type implement these; but I think that this it is a reasonable assumption that it does. 

With this change, the practical bounds of ForIRI would be `Borrow<str> + Clone + From<String>`
with all the others required by `Borrow<str>`.

**Comment by phillord** [comment]
I have tested this now. If I update pretty_rdf to use `Borrow<str>` bounds (which it probably should have anyway), then it is straight-forward to drop `AsRef<A>`.  In practice, as horned_owl requires `Borrow`, I think, I could do this without updating pretty_rdf also, but it would require some kind of newtype adaptor to make it work which would be a PITA in several places. Most of the code changes required in pretty_rdf are trivial (i.e. called `borrow` not `as_ref`) with a single case where a type annotation was needed to avoid a fairly incomprehensible error 

All of this means we could drop `Eq`, `Ord`, `Hash` and the two partials since we could use `A.borrow() ==` or equivalent every where we currently use a direct comparison. `IRI` already implements `Deref<item=str>` (which just defers to `borrow`), so `IRI="http://example.com` should work anyway.

So, it just remains to consider whether this is a good thing. All the types that I have used for `A`  (`Rc<str>`, `Arc<str>` and `String`) do all implement `Eq` and the others directly. I think it makes sense to drop `AsRef` as requiring both seems silly; for the rest, I think will consider over the weekend and then decide.

**Comment by phillord** [comment]
I have thought this through now. I am know that you have made a lot of changes and put a significant amount of work into this, but I have decided that I am not going to take the PR. I think it adds complexity to the code base and I am not clear why we need it.

`ForIRI` is a hack because `Rc<str>` and `Arc<str>` and `String` lack a defining trait. As it stands, `ForIRI` simply implements all the traits that these types do. In time, something like the `PointerFamily` trait mentioned in the [rust blog](https://blog.rust-lang.org/2021/08/03/GATs-stabilization-push.html) may get into the standard library; but at the time of writing the code, GATs were not available, and who knows when standard support may come.

Now there are undoubtedly changes in this code that we should make. For example, this is clearly a good thing. 

```rust
ClassExpression::Class(cls)
                        if cls.0.as_ref() == crate::vocab::OWL::Thing.as_ref()

// to this

ClassExpression::Class(cls) if cls.is_thing()
```

On the other hand, we are introducing a lot of type annotations. Removing `as_ref` here has resulted in this change which I think is less readable.


```rust 
ont.i()
                .the_ontology_id_or_default()
                .iri
                .as_ref()
                .unwrap()
                .as_ref(),

// to this
Borrow::<str>::borrow(ont.i().the_ontology_id_or_default().iri.as_ref().unwrap()),
```

We see a similar story in the test sets. This modification is clearly a step back in terms of readability.


```rust
assert_eq!(
            RDF::First.as_ref(),
            "http://www.w3.org/1999/02/22-rdf-syntax-ns#first"
        );

// to this
assert_eq!(
            Borrow::<str>::borrow(&RDF::First),
            "http://www.w3.org/1999/02/22-rdf-syntax-ns#first"
       );
```

While you have not got to it yet, the RDF reader will require bounds on pretty much every method; I already did give it a go.

Having thought a lot about this, however, I think you have highlighted a problem. When I wrote the code, I didn't really understand the difference between `AsRef` and `Borrow`; I think, actually, I still do not entirely, but at least I am further along the road. And then, of course, there is `Deref`. What I have discovered is I am using all three of these inconsistently; and some of the definitions make no real sense. For example, this definition defers `Deref` to borrow, although all the likely implementing types implement `Deref<target=str>`.

```rust
impl<A: ForIRI> Deref for IRI<A> {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        self.0.borrow()
    }
}
```

And, through out the code base there is wide inconsistency on which interface I actually use -- calls to `as_ref` and `borrow` are randomly sprinkled throughout.

My conclusions from all of this:

 - The `ForIRI` type actually needs to be extended to include `Deref`.
 - All the new types (IRI, named entities, anonymous individual and NamedEntity enums maybe) should implement `Borrow`, `Deref`, `AsRef`  (to `str`); also `Hash`, `Ord`, `Eq` which I think they already do. Probably we should use `derive_more`.
 - We should use derefencing where ever possible
 - We should use `borrow` where the standard library uses `borrow` (i.e. various maps) and `as_ref` where we just need a `str`.
 - We should seek to minimize `.borrow` and `.as_ref` calls.

Equality and to a lesser extent ordering require a little thought. I think these should remain type specific; you should not be able to compare two named entities of different kinds without doing this explicitly.

```rust
let c = b.class("http://www.example.com")
let i = b.individual("http://www.example.com")

// compile error and should be a compile error
assert_eq(c, i);
```

But we should provide better support for IRI based comparison. We already have `.is`, but I think it is not general enough.

```rust
let brc = Build::new_rc();
let barc = Build::new_arc();

// compile error but should work
assert!(brc.is(barc))
```

This one has very practical consequences because the vocab module is
`IRI<String>`. If we implement this correctly we should be able to do things like:


```rust
ClassExpression::Class(cls) if cls.is(OWL::Thing);
assert!(
    &RDF::First.is("http://www.w3.org/1999/02/22-rdf-syntax-ns#first")
);
```

with an implementation which looks a little like this:

```rust
impl<A: ForIRI> Class<A> {
    pub fn is<B, I>(&self, iri: I) -> bool
               where 
               B:ForIRI,
               I:Into<&IRI<B>>
    {
        self.0.is(iri.into())
    }

    pub fn is_s<S>(&self, iri:S) -> bool
              where S:Into<str>
    {
        self.into() == iri.into()
    }
}
```

It is not clear to me that we actually need the two methods `is` and `is_s`. I think in horned_owl we would only ever need `IRI` to `IRI` comparison, and it adds a little bit of newtype type safety; in the test above we are using `IRI` to `str` comparison which would be the exception.

The last question for me is when. My initial answer is for Horned-OWL 2.0. In terms of forward planning, I think removing paper cuts, regularising the API and making it go faster are the obvious aims for 2.0 and all of these changes fit into the first two.

**Comment by filippodebortoli** [comment]
> The last question for me is when. My initial answer is for Horned-OWL 2.0. In terms of forward planning, I think removing paper cuts, regularising the API and making it go faster are the obvious aims for 2.0 and all of these changes fit into the first two.

Yes, I agree with you.

> I think in horned_owl we would only ever need IRI to IRI comparison

Ok. Do you think that there can be cases where a comparison between `IRI<A: ForIRI>` and `IRI<B: ForIRI>` is required? Assuming that `ForIRI: Deref<Target = str>`, one idea could be to implement `PartialEq<IRI<B>> where B: ForIRI` for `IRI<A: ForIRI>` and use

```rust
    fn eq(&self, other: &IRI<B>) -> bool {
        **self == **other
    }
```

where the double dereferencing makes it so that we are comparing `str`s.

Anything that encapsulates `IRI<A>`, like named entities and anonymous individuals, could then implement `Deref<Target = IRI<A>>`, so that:

+ we can keep a type-safe comparison by deriving `PartialEq` so that e.g. a class and an individual are correctly evaluated as different, and
+ implement `is(&self, other: &impl Deref<Target = IRI<B: ForIRI>>)` simply as `**self == **other` again and have a method to compare IRIs.

Regarding the rest, I think that I have no bad feelings about the PR getting rejected, and I can still factor out the changes that are more in line with your proposal into a new PR, since I was already working e.g. on adopting dereferencing where possible. :-)

**Comment by phillord** [comment]
> Do you think that there can be cases where a comparison between `IRI<A: ForIRI>` and `IRI<B: ForIRI>` is required?

Yes. The meta data from vocab is `IRI<String>`. We don't need to implement this through equality but, for me, it would be a naturalistic implementation for `is`. This would dereference from the `NamedEntity` to the underlying `IRI` and then use `==`.

I can't see a use case for `Class<A>` to `Class<B>` equality; if `IRI<A>` to `IRI<B>` is comparable, of course, there is a straight-forward implementation path; but the `derive` macro wouldn't work for this, so I am not sure it is worth the effort.

I guess that leaves a rather ugly asymmetric between `IRI` and `Class`; so, maybe, indeed, we should only support `IRI<A>` to `IRI<B>` comparison through an `is` method.
